language: node_js
node_js:
  - "6.9.1"

env:
  - CC=gcc-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
      - sudo add-apt-repository ppa:git-core/ppa -y
      - sudo apt-get update -q
      - sudo apt-get install git -y
      - git version
      - cd node

install:
      - npm install

script:
      - npm test

notifications:
  email: false
